server:
  port: 2003
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.171.199:3306/os_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 192.168.171.199:8848
  redis:
    host: 192.168.171.199
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
logging:
  level:
    com.ninep.user: debug
feign:
  circuitbreaker:
    enabled: true

seata:
  enabled: true
  application-id: user-service
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  service:
    vgroup-mapping:
      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.171.199:8848
      namespace: 5e6e5510-c664-4d88-a790-17c046b97b8a
      cluster: default
      group: SEATA_GROUP
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      namespace: 5e6e5510-c664-4d88-a790-17c046b97b8a
      server-addr: 192.168.171.199:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      dataId: seataServer.properties
